import { CategoryItem, Customer, Expense, FinishingItem, MachineItem, MaterialItem, Order, ProductSizeVariant, StoreSettings, User } from '../types';

export const createApparelSizeVariants = (
  baseSell: number,
  baseCost: number,
  baseStock: number = 100
): ProductSizeVariant[] => [
  { id: 'v-s', size: 'S', sellingPrice: baseSell - 5000, costPrice: Math.round(baseCost * 0.95), stock: Math.round(baseStock * 0.25) },
  { id: 'v-m', size: 'M', sellingPrice: baseSell, costPrice: baseCost, stock: Math.round(baseStock * 0.35) },
  { id: 'v-l', size: 'L', sellingPrice: baseSell + 5000, costPrice: Math.round(baseCost * 1.05), stock: Math.round(baseStock * 0.25) },
  { id: 'v-xl', size: 'XL', sellingPrice: baseSell + 10000, costPrice: Math.round(baseCost * 1.10), stock: Math.round(baseStock * 0.15) },
];

export const initialCategories: CategoryItem[] = [
  { id: 'CAT-1', name: 'INDOOR', desc: 'Cetak indoor resolusi tinggi: Albatros, Luster, Canvas, Stiker Vinyl Indoor, X-Banner' },
  { id: 'CAT-2', name: 'OUTDOOR', desc: 'Cetak spanduk banner outdoor tahan panas & cuaca, Baliho, Backlite, Plang Toko' },
];

export const initialUsers: User[] = [
  {
    id: 'USR-001',
    name: 'Yahya (Owner)',
    username: 'owner',
    pin: '1234',
    role: 'owner',
    phone: '0812-8888-9999',
    active: true,
  },
  {
    id: 'USR-002',
    name: 'Sinta (Kasir / Admin)',
    username: 'kasir',
    pin: '1111',
    role: 'admin',
    phone: '0813-1111-2222',
    active: true,
  },
  {
    id: 'USR-003',
    name: 'Rian (Graphic Designer)',
    username: 'designer',
    pin: '2222',
    role: 'designer',
    phone: '0815-3333-4444',
    active: true,
  },
  {
    id: 'USR-004',
    name: 'Budi (Operator Cetak)',
    username: 'operator',
    pin: '3333',
    role: 'operator',
    phone: '0817-5555-6666',
    active: true,
  },
];

export const initialMaterials: MaterialItem[] = [
  // OUTDOOR PRODUCTS
  {
    id: 'MAT-001',
    name: 'Flexi China 280gr (Spanduk Banner Standar)',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 8000,
    sellingPrice: 16000,
    stock: 450,
    minStock: 100,
    description: 'Spanduk ekonomis warung, promosi jalan, event singkat',
  },
  {
    id: 'MAT-002',
    name: 'Flexi Korchin / Korea 440gr (Tebal Awet)',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 16000,
    sellingPrice: 28000,
    stock: 280,
    minStock: 50,
    description: 'Billboard, plang toko, backdrop premium tahan panas/hujan',
  },
  {
    id: 'MAT-003',
    name: 'Flexi Jerman 510gr (Billboard / Plang Toko)',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 25000,
    sellingPrice: 45000,
    stock: 150,
    minStock: 30,
    description: 'Plang toko super awet tebal premium tahan cuaca ekstrem',
  },
  {
    id: 'MAT-004',
    name: 'Flexi Backlite 510gr (Neonbox Lampu)',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 28000,
    sellingPrice: 50000,
    stock: 120,
    minStock: 25,
    description: 'Bahan tembus cahaya untuk box neon sign lampu jalan',
  },
  {
    id: 'MAT-005',
    name: 'Spanduk Kain TC / Peles (Kain Umbul-umbul)',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 12000,
    sellingPrice: 22000,
    stock: 200,
    minStock: 40,
    description: 'Spanduk bahan kain ringan berkibar untuk event & bendera',
  },
  {
    id: 'MAT-006',
    name: 'Sticker Oneway Vision (Kaca Mobil / Toko)',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 30000,
    sellingPrice: 55000,
    stock: 90,
    minStock: 20,
    description: 'Stiker berpori untuk kaca toko / mobil dari dalam tembus pandang',
  },

  // INDOOR PRODUCTS
  {
    id: 'MAT-007',
    name: 'Albatros Matte + Standing X-Banner 60x160',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 40000,
    sellingPrice: 75000,
    stock: 65,
    minStock: 20,
    description: 'Ukuran 60x160cm halus indoor tanpa serat + standing fiber',
  },
  {
    id: 'MAT-008',
    name: 'Albatros Matte + Standing Y-Banner 60x160',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 45000,
    sellingPrice: 85000,
    stock: 50,
    minStock: 15,
    description: 'Banner indoor rangka besi kokoh tahan hembusan AC',
  },
  {
    id: 'MAT-009',
    name: 'Roll Up Banner Aluminium 60x160cm',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 95000,
    sellingPrice: 175000,
    stock: 40,
    minStock: 10,
    description: 'Standing roll up otomatis tarik bahan albatros mewah',
  },
  {
    id: 'MAT-010',
    name: 'Sticker Vinyl Ritrama + Cutting Kiss Cut',
    category: 'INDOOR',
    unit: 'm²',
    costPrice: 35000,
    sellingPrice: 65000,
    stock: 120,
    minStock: 30,
    description: 'Stiker resolusi tinggi tahan air + cutting pola presisi',
  },
  {
    id: 'MAT-011',
    name: 'Sticker Transparan Glossy + Cutting',
    category: 'INDOOR',
    unit: 'm²',
    costPrice: 38000,
    sellingPrice: 70000,
    stock: 85,
    minStock: 20,
    description: 'Stiker bening transparan kilap untuk kemasan botol & kaca',
  },
  {
    id: 'MAT-012',
    name: 'Luster Paper Foto High Resolution',
    category: 'INDOOR',
    unit: 'm²',
    costPrice: 32000,
    sellingPrice: 60000,
    stock: 95,
    minStock: 25,
    description: 'Kertas foto kulit jeruk anti silau tajam untuk pigura & galeri',
  },
  {
    id: 'MAT-013',
    name: 'Canvas Lukis Cotton + Spanram Kayu',
    category: 'INDOOR',
    unit: 'm²',
    costPrice: 65000,
    sellingPrice: 120000,
    stock: 45,
    minStock: 10,
    description: 'Kain kanvas asli berserat seni lukisan + rangka spanram kayu',
  },

  // ================= SHOPEE INTEGRATED PRODUCTS =================
  // OUTDOOR: BANNER, STIKER & BENDERA
  {
    id: 'SHP-25436897810',
    name: 'Banner Custom Murah Free Desain',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 12000,
    sellingPrice: 20000,
    stock: 250,
    minStock: 50,
    description: 'Spanduk banner outdoor murah free desain bahan tebal awet',
  },
  {
    id: 'SHP-27765036971',
    name: 'Bendera Custom',
    category: 'OUTDOOR',
    unit: 'm²',
    costPrice: 18000,
    sellingPrice: 30000,
    stock: 150,
    minStock: 30,
    description: 'Harga diatas adalah harga bendera / spanduk kain berkibar outdoor',
  },
  {
    id: 'SHP-28163427209',
    name: 'STIKER CROMO / STIKER KEMASAN A3+',
    category: 'OUTDOOR',
    unit: 'lbr',
    costPrice: 5000,
    sellingPrice: 10000,
    stock: 500,
    minStock: 50,
    description: 'Cetak Stiker Kromo Kemasan Ukuran A3+ tahan cuaca & label kemasan',
  },

  // INDOOR: SABLON & MERCHANDISE
  {
    id: 'SHP-26113603420',
    name: 'Sablon DTF Meteran Per Meter Instant',
    category: 'INDOOR',
    unit: 'meter',
    costPrice: 25000,
    sellingPrice: 45000,
    stock: 200,
    minStock: 30,
    description: 'High quality sablon DTF meteran cetak tajam siap press kain',
  },
  {
    id: 'SHP-26474080418',
    name: 'Kaos Sablon Custom Satuan | Free Desain',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 35000,
    sellingPrice: 55000,
    stock: 150,
    minStock: 25,
    description: 'Kaos sablon combed custom satuan bebas desain',
  },
  {
    id: 'SHP-29961405175',
    name: 'ID Card / Kartu Nama',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 2500,
    sellingPrice: 5000,
    stock: 300,
    minStock: 50,
    description: 'Bisa bikin satuan / borongan lebih murah bahan PVC & art carton',
  },

  // INDOOR: JERSEY PRINTING (Bahan 100% Polyester Drifit)
  {
    id: 'SHP-29810850537',
    name: 'Jersey Motor Free Custom – Nama, Nomor, Logo',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 100,
    minStock: 15,
    description: 'Bahan 100% polyester drifit sublimasi full print motor',
  },
  {
    id: 'SHP-27310855091',
    name: 'Jersey Bola Free Custom – Nama, Nomor, Logo',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 100,
    minStock: 15,
    description: 'Bahan 100% polyester drifit jersey sepak bola & futsal',
  },
  {
    id: 'SHP-46016186126',
    name: 'Jersey Custom Full Printing Hoodie + Tali',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 75000,
    sellingPrice: 125000,
    stock: 80,
    minStock: 10,
    description: 'Bahan 100% polyester drifit model hoodie kupluk bertali',
  },
  {
    id: 'SHP-50566175625',
    name: 'Jersey Custom Full Printing Sleting',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 65000,
    sellingPrice: 110000,
    stock: 80,
    minStock: 10,
    description: 'Bahan 100% polyester drifit full zipper sleting depan',
  },
  {
    id: 'SHP-40864835369',
    name: 'Baju Jersey Custom Design (SUKA SUKA)',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 120,
    minStock: 20,
    description: 'Bahan 100% polyester drifit bebas custom motif apa saja',
  },
  {
    id: 'SHP-26490401360',
    name: 'Jersey Custom Lengan Pendek (DESIGN SUKA SUKA)',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 48000,
    sellingPrice: 80000,
    stock: 120,
    minStock: 20,
    description: 'Bahan 100% polyester drifit lengan pendek adem & cepat kering',
  },
  {
    id: 'SHP-47265733862',
    name: 'Jersey Anime OnePiece Unisex Oversize Dryfit',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 55000,
    sellingPrice: 90000,
    stock: 90,
    minStock: 15,
    description: 'Bahan 100% polyester drifit motif anime jepang oversize trendy',
  },
  {
    id: 'SHP-25588040878',
    name: 'Jersey Trail Free Custom – Nama, Nomor, Logo',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 85,
    minStock: 15,
    description: 'Bahan 100% polyester drifit untuk trail adventure & trabas',
  },
  {
    id: 'SHP-26740411380',
    name: 'Baju Jersey Polo Custom Design (SUKA SUKA)',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 60000,
    sellingPrice: 95000,
    stock: 75,
    minStock: 10,
    description: 'Bahan 100% polyester drifit berkerah polo kancing rapi',
  },
  {
    id: 'SHP-54508233156',
    name: 'Baju Jersey MOTOCROSS DRIFIT',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 100,
    minStock: 15,
    description: 'Bahan 100% polyester drifit khusus motocross balap sirkuit',
  },
  {
    id: 'SHP-28190079078',
    name: 'Baju Jersey Custom Motor DRIFIT',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 100,
    minStock: 15,
    description: 'Bahan 100% polyester drifit jersey komunitas motor',
  },
  {
    id: 'SHP-44551092728',
    name: 'Baju Jersey Custom Riding DRIFIT',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 100,
    minStock: 15,
    description: 'Bahan 100% polyester drifit jersey touring & riding harian',
  },
  {
    id: 'SHP-26710850765',
    name: 'Jersey Voli Free Custom – Nama, Nomor, Logo',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 90,
    minStock: 15,
    description: 'Bahan 100% polyester drifit untuk tim bola voli putra/putri',
  },
  {
    id: 'SHP-26583717865',
    name: 'Jersey Bola Custom Timnas Dewasa & Anak',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 120,
    minStock: 20,
    description: 'Bahan 100% polyester drifit edisi timnas tersedia size anak & dewasa',
  },
  {
    id: 'SHP-26834143480',
    name: 'Jersey Motor Free Custom – Seri 2',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 80,
    minStock: 15,
    description: 'Bahan 100% polyester drifit variasi corak racing motor series 2',
  },
  {
    id: 'SHP-51501053211',
    name: 'Jersey Racing motif bunga | Custom | Full Printing',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 55000,
    sellingPrice: 90000,
    stock: 70,
    minStock: 10,
    description: 'Bahan 100% polyester drifit motif bunga floral aesthetic printing',
  },
  {
    id: 'SHP-53751068957',
    name: 'Jersey Motocross | Custom | Full Printing',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 55000,
    sellingPrice: 90000,
    stock: 85,
    minStock: 15,
    description: 'Bahan 100% polyester drifit full sublimasi cerah tahan luntur',
  },
  {
    id: 'SHP-44126253998',
    name: 'Jersey Racing motif dayak | Custom | Full Printing',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 55000,
    sellingPrice: 90000,
    stock: 75,
    minStock: 10,
    description: 'Bahan 100% polyester drifit motif ukir etnik dayak kalimantan',
  },
  {
    id: 'SHP-29060850599',
    name: 'Jersey Game Free Custom – Nama, Logo',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 50000,
    sellingPrice: 85000,
    stock: 90,
    minStock: 15,
    description: 'Bahan 100% polyester drifit untuk squad game esport mobile legends, pubg',
  },
  {
    id: 'SHP-26723038671',
    name: 'JERSEY BOLA SETELAN CUSTOM',
    category: 'INDOOR',
    unit: 'setel',
    costPrice: 70000,
    sellingPrice: 115000,
    stock: 100,
    minStock: 20,
    description: 'Bahan 100% polyester drifit 1 setel lengkap baju plus celana',
  },

  // INDOOR: JAKET WINDBREAKER & RACING (Waterproof)
  {
    id: 'SHP-41214829232',
    name: 'Jaket WINDBREAKER Custom – (DESIGN SUKA SUKA)',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 95000,
    sellingPrice: 150000,
    stock: 60,
    minStock: 10,
    description: 'Jaket Custom Waterproof windbreaker tahan angin & hujan ringan',
  },
  {
    id: 'SHP-55811054253',
    name: 'Nascar Windbreaker Style Varsity Series',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 105000,
    sellingPrice: 165000,
    stock: 50,
    minStock: 10,
    description: 'Jaket Nascar Style Varsity Waterproof model kerah varsity kekinian',
  },
  {
    id: 'SHP-47515190605',
    name: 'Jaket Motor Windbreaker YAMAHA',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 55,
    minStock: 10,
    description: 'Jaket motif Yamaha menggunakan bahan parasut taslan waterproof',
  },
  {
    id: 'SHP-44033146073',
    name: 'Jaket Windbreaker Volley',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 95000,
    sellingPrice: 145000,
    stock: 45,
    minStock: 10,
    description: 'Jaket Custom Waterproof windbreaker untuk tim voli & olahraga',
  },
  {
    id: 'SHP-41282549644',
    name: 'Jaket Custom Suka" Model Raglan',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 95000,
    sellingPrice: 150000,
    stock: 50,
    minStock: 10,
    description: 'Jaket Custom Waterproof kombinasi potongan lengan model raglan',
  },
  {
    id: 'SHP-56859388653',
    name: 'Jaket Nascar Custom | Desain Sesukamu',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 105000,
    sellingPrice: 165000,
    stock: 55,
    minStock: 10,
    description: 'Jaket Custom Waterproof gaya nascar racing bordir/printing bebas',
  },
  {
    id: 'SHP-42213658206',
    name: 'Jaket Custom Nascar – Free Desain Nama & Nomor',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 105000,
    sellingPrice: 165000,
    stock: 60,
    minStock: 10,
    description: 'Jaket Custom Waterproof gratis custom nama punggung & nomor start',
  },
  {
    id: 'SHP-40963658531',
    name: 'Jaket Street Custom Windbreaker – Free Desain',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 95000,
    sellingPrice: 150000,
    stock: 50,
    minStock: 10,
    description: 'Jaket Custom Waterproof style streetwear kasual pria & wanita',
  },
  {
    id: 'SHP-29890081282',
    name: 'Jaket Racing cars 2 Custom Windbreaker',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 40,
    minStock: 10,
    description: 'Jaket Custom Waterproof edisi karakter racing cars lightning mcqueen',
  },
  {
    id: 'SHP-48451089675',
    name: 'Jaket Racing Windbreaker | Custom Waterproof',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 50,
    minStock: 10,
    description: 'Jaket Custom Waterproof bahan taslan ripstop windproof',
  },
  {
    id: 'SHP-43526160495',
    name: 'Jaket Custom Windbreaker – Free Desain',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 95000,
    sellingPrice: 150000,
    stock: 50,
    minStock: 10,
    description: 'Jaket Custom Waterproof cocok untuk seragam kantor & komunitas',
  },
  {
    id: 'SHP-43963671401',
    name: 'Jaket Racing Custom Windbreaker Series 1',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 40,
    minStock: 10,
    description: 'Jaket Custom Waterproof motif balap road race series 1',
  },
  {
    id: 'SHP-42659243370',
    name: 'Jaket Racing Custom Windbreaker Series 2',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 40,
    minStock: 10,
    description: 'Jaket Custom Waterproof motif balap drag bike series 2',
  },
  {
    id: 'SHP-28790072073',
    name: 'Jaket Racing Custom Windbreaker Series 3',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 40,
    minStock: 10,
    description: 'Jaket Custom Waterproof motif balap supermoto series 3',
  },
  {
    id: 'SHP-26337016216',
    name: 'Jaket Racing Custom Windbreaker Series 4',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 40,
    minStock: 10,
    description: 'Jaket Custom Waterproof motif balap grasstrack series 4',
  },
  {
    id: 'SHP-48100689751',
    name: 'Jaket Racing Custom Windbreaker Series 5',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 40,
    minStock: 10,
    description: 'Jaket Custom Waterproof motif sponsor racing series 5',
  },
  {
    id: 'SHP-28471387979',
    name: 'Jaket Racing Custom Windbreaker Series 6',
    category: 'INDOOR',
    unit: 'pcs',
    costPrice: 100000,
    sellingPrice: 155000,
    stock: 40,
    minStock: 10,
    description: 'Jaket Custom Waterproof motif striping modern series 6',
  },
];

export const initialFinishing: FinishingItem[] = [
  { id: 'FIN-001', name: 'Mata Ayam 4 Sudut', category: 'large_format', price: 2000, unit: 'per_pcs', description: 'Ring besi di tiap pojok spanduk' },
  { id: 'FIN-002', name: 'Mata Ayam Keliling (per meter)', category: 'large_format', price: 1000, unit: 'per_meter', description: 'Ring besi jarak 1 meter keliling' },
  { id: 'FIN-003', name: 'Seaming / Lipat Press Keliling', category: 'large_format', price: 0, unit: 'flat', description: 'Lipatan tepi spanduk rapi & kuat' },
  { id: 'FIN-004', name: 'Kolong Selongsong Kanan Kiri', category: 'large_format', price: 3000, unit: 'per_pcs', description: 'Untuk dimasukkan bambu/kayu' },
  { id: 'FIN-005', name: 'Laminasi Doff A3+', category: 'digital_a3', price: 2500, unit: 'per_lembar', description: 'Lapisan doff elegan anti sidik jari' },
  { id: 'FIN-006', name: 'Laminasi Glossy A3+', category: 'digital_a3', price: 2000, unit: 'per_lembar', description: 'Lapisan kilap proteksi gores & air' },
  { id: 'FIN-007', name: 'Potong Kiss Cut (Setengah Putus)', category: 'digital_a3', price: 2000, unit: 'per_lembar', description: 'Siap cabut per stiker di lembaran' },
  { id: 'FIN-008', name: 'Potong Die Cut (Putus Satuan)', category: 'digital_a3', price: 3000, unit: 'per_lembar', description: 'Potong bentuk pola tembus' },
  { id: 'FIN-009', name: 'Jilid Spiral Kawat + Mika', category: 'digital_a3', price: 10000, unit: 'per_pcs', description: 'Untuk kalender dinding/meja atau proposal' },
];

export const initialMachines: MachineItem[] = [
  { id: 'MCH-001', name: 'Galaxy Konica 512i (Outdoor 3.2m)', type: 'outdoor', brand: 'Galaxy', status: 'running', currentJob: 'Spanduk Warung Kopi Senja' },
  { id: 'MCH-002', name: 'Epson SureColor S80670 (Indoor 9 Color)', type: 'indoor', brand: 'Epson', status: 'idle' },
  { id: 'MCH-003', name: 'Konica Minolta AccurioPress C4065 (A3+)', type: 'digital_a3', brand: 'Konica Minolta', status: 'running', currentJob: 'Brosur Perumahan Citra' },
  { id: 'MCH-004', name: 'Rhinotec DTF 60cm Double Head', type: 'dtf', brand: 'Rhinotec', status: 'idle' },
  { id: 'MCH-005', name: 'Graphtec CE7000-60 Cutting Plotter', type: 'cutting', brand: 'Graphtec', status: 'idle' },
];

export const initialCustomers: Customer[] = [
  {
    id: 'CUST-001',
    name: 'Toko Kopi Senja (Mas Rendy)',
    phone: '081234567890',
    email: 'kopisenja@gmail.com',
    company: 'Kopi Senja Nusantara',
    address: 'Jl. Pemuda No. 12, Bandung',
    type: 'reseller',
    totalOrders: 14,
    totalSpent: 4850000,
    unpaidBalance: 0,
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'CUST-002',
    name: 'PT Maju Bersama Advertising',
    phone: '081987654321',
    email: 'procurement@majubersama.co.id',
    company: 'PT Maju Bersama',
    address: 'Kawasan Industri Cikarang Blok C-4',
    type: 'corporate',
    totalOrders: 28,
    totalSpent: 24600000,
    unpaidBalance: 1200000,
    createdAt: '2026-01-15T08:30:00Z',
  },
  {
    id: 'CUST-003',
    name: 'Ibu Ratna Dewi',
    phone: '085712345678',
    email: 'ratnadewi88@gmail.com',
    company: 'Dapur Mama Ratna (Catering)',
    address: 'Komplek Antapani Indah No. 5',
    type: 'regular',
    totalOrders: 5,
    totalSpent: 920000,
    unpaidBalance: 0,
    createdAt: '2026-03-01T14:15:00Z',
  },
  {
    id: 'CUST-004',
    name: 'Sekolah Bintang Harapan',
    phone: '081399887766',
    email: 'tatausaha@bintangharapan.sch.id',
    company: 'Yayasan Bintang Harapan',
    address: 'Jl. Pendidikan No. 45',
    type: 'corporate',
    totalOrders: 8,
    totalSpent: 6750000,
    unpaidBalance: 500000,
    createdAt: '2026-02-20T11:00:00Z',
  },
  {
    id: 'CUST-005',
    name: 'Komunitas Motor CB Indonesia',
    phone: '087811223344',
    email: 'cbrider.bdg@gmail.com',
    company: 'CB Club Bandung',
    address: 'Jl. Riau No. 104',
    type: 'regular',
    totalOrders: 3,
    totalSpent: 1875000,
    unpaidBalance: 0,
    createdAt: '2026-04-05T16:00:00Z',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ORD-001',
    orderNumber: 'INV-202608-0001',
    spkNumber: 'SPK-202608-0001',
    customerId: 'CUST-001',
    customerName: 'Toko Kopi Senja (Mas Rendy)',
    customerPhone: '081234567890',
    customerType: 'reseller',
    items: [
      {
        id: 'ITEM-001',
        category: 'large_format',
        productName: 'Spanduk Menu Banner Outdoor',
        materialName: 'Flexi China 280gr (Outdoor)',
        lengthM: 3.0,
        widthM: 1.0,
        areaM2: 3.0,
        qty: 2,
        unit: 'm²',
        unitPrice: 16000,
        subtotal: 96000,
        finishingNames: ['Mata Ayam 4 Sudut', 'Seaming / Lipat Press Keliling'],
        finishingCost: 4000,
        designFee: 0,
        designType: 'ready_to_print',
        fileUrl: 'https://drive.google.com/spanduk_kopi_fix.tiff',
        fileName: 'spanduk_kopi_fix.tiff',
        targetMachine: 'Galaxy Konica 512i (Outdoor 3.2m)',
        notes: 'Warna kopi dibuat pekat, mata ayam keling rapi',
      },
    ],
    subtotal: 100000,
    discount: 0,
    tax: 0,
    total: 100000,
    paidAmount: 100000,
    balance: 0,
    paymentStatus: 'paid',
    paymentMethod: 'qris',
    status: 'production',
    priority: 'normal',
    deadline: new Date(Date.now() + 86400000).toISOString(),
    createdBy: 'Sinta (Kasir / Admin)',
    operatorId: 'USR-004',
    operatorName: 'Budi (Operator Cetak)',
    designStatus: 'approved',
    designNotes: 'File siap cetak resolusi 150 DPI CMYK',
    pickupType: 'pickup',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    timeline: [
      {
        id: 'TL-1',
        timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
        status: 'pending',
        user: 'Sinta (Kasir)',
        userRole: 'admin',
        note: 'Pesanan masuk dan pembayaran lunas via QRIS',
      },
      {
        id: 'TL-2',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        status: 'production',
        user: 'Budi (Operator)',
        userRole: 'operator',
        note: 'Mulai proses cetak di mesin Galaxy Konica',
      },
    ],
  },
  {
    id: 'ORD-002',
    orderNumber: 'INV-202608-0002',
    spkNumber: 'SPK-202608-0002',
    customerId: 'CUST-002',
    customerName: 'PT Maju Bersama Advertising',
    customerPhone: '081987654321',
    customerType: 'corporate',
    items: [
      {
        id: 'ITEM-002',
        category: 'digital_a3',
        productName: 'Brosur Perumahan Grand Harmony',
        materialName: 'Art Paper 150gr A3+ (Flyer / Brosur)',
        qty: 300,
        unit: 'lembar',
        unitPrice: 4500,
        subtotal: 1350000,
        finishingNames: ['Laminasi Glossy A3+'],
        finishingCost: 600000,
        designFee: 150000,
        designType: 'new_design',
        fileUrl: 'https://drive.google.com/bahan_brosur_grandharmony.zip',
        fileName: 'bahan_brosur_grandharmony.zip',
        targetMachine: 'Konica Minolta AccurioPress C4065 (A3+)',
        notes: 'Lipat 3 (Z-Fold), logo perumahan emas mengkilap',
      },
    ],
    subtotal: 2100000,
    discount: 100000,
    tax: 0,
    total: 2000000,
    paidAmount: 800000,
    balance: 1200000,
    paymentStatus: 'dp',
    paymentMethod: 'transfer_bca',
    status: 'design',
    priority: 'urgent',
    deadline: new Date(Date.now() + 86400000 * 2).toISOString(),
    createdBy: 'Sinta (Kasir / Admin)',
    designerId: 'USR-003',
    designerName: 'Dimas (Designer Grafis)',
    designStatus: 'in_progress',
    designNotes: 'Sedang buat draft alternatif 1 dan 2',
    proofPreviewUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
    pickupType: 'delivery',
    deliveryAddress: 'PT Maju Bersama, Kawasan Industri Cikarang Blok C-4',
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    timeline: [
      {
        id: 'TL-3',
        timestamp: new Date(Date.now() - 3600000 * 8).toISOString(),
        status: 'pending',
        user: 'Sinta (Kasir)',
        userRole: 'admin',
        note: 'Order masuk DP Rp 800.000 BCA, sisa pelunasan saat selesai',
      },
      {
        id: 'TL-4',
        timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
        status: 'design',
        user: 'Dimas (Designer)',
        userRole: 'designer',
        note: 'Dimas mengambil tugas desain & sedang menyusun layout brosur',
      },
    ],
  },
  {
    id: 'ORD-003',
    orderNumber: 'INV-202608-0003',
    spkNumber: 'SPK-202608-0003',
    customerId: 'CUST-005',
    customerName: 'Komunitas Motor CB Indonesia',
    customerPhone: '087811223344',
    customerType: 'regular',
    items: [
      {
        id: 'ITEM-003',
        category: 'merchandise',
        productName: 'Kaos Anniversary CB Club Black',
        materialName: 'Kaos Cotton Combed 30s + Cetak DTF A3',
        qty: 25,
        unit: 'pcs',
        unitPrice: 75000,
        subtotal: 1875000,
        finishingNames: [],
        finishingCost: 0,
        designFee: 0,
        designType: 'ready_to_print',
        fileUrl: 'https://drive.google.com/kaos_cb_anniv_vector.ai',
        fileName: 'kaos_cb_anniv_vector.ai',
        targetMachine: 'Rhinotec DTF 60cm Double Head',
        notes: 'Ukuran kaos: M (10), L (10), XL (5)',
      },
    ],
    subtotal: 1875000,
    discount: 0,
    tax: 0,
    total: 1875000,
    paidAmount: 1875000,
    balance: 0,
    paymentStatus: 'paid',
    paymentMethod: 'transfer_bca',
    status: 'ready',
    priority: 'normal',
    deadline: new Date(Date.now() + 3600000 * 5).toISOString(),
    createdBy: 'Sinta (Kasir / Admin)',
    operatorId: 'USR-004',
    operatorName: 'Budi (Operator Cetak)',
    designStatus: 'approved',
    pickupType: 'pickup',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    timeline: [
      {
        id: 'TL-5',
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
        status: 'pending',
        user: 'Sinta (Kasir)',
        userRole: 'admin',
        note: 'Order diterima, bayar lunas',
      },
      {
        id: 'TL-6',
        timestamp: new Date(Date.now() - 86400000).toISOString(),
        status: 'production',
        user: 'Budi (Operator)',
        userRole: 'operator',
        note: 'Cetak DTF dan proses press kaos selesai',
      },
      {
        id: 'TL-7',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        status: 'ready',
        user: 'Sinta (Kasir)',
        userRole: 'admin',
        note: 'Pesanan sudah di packing dan siap diambil customer',
      },
    ],
  },
  {
    id: 'ORD-004',
    orderNumber: 'INV-202608-0004',
    spkNumber: 'SPK-202608-0004',
    customerId: 'CUST-003',
    customerName: 'Ibu Ratna Dewi',
    customerPhone: '085712345678',
    customerType: 'regular',
    items: [
      {
        id: 'ITEM-004',
        category: 'digital_a3',
        productName: 'Stiker Label Sambal Kemasan Botol',
        materialName: 'Stiker Chromo / Kromo A3+ (Cetak & Kiss Cut)',
        qty: 30,
        unit: 'lembar',
        unitPrice: 10000,
        subtotal: 300000,
        finishingNames: ['Potong Kiss Cut (Setengah Putus)'],
        finishingCost: 60000,
        designFee: 50000,
        designType: 'minor_edit',
        targetMachine: 'Konica Minolta AccurioPress C4065 (A3+)',
        notes: 'Diameter stiker bulat 5cm (1 lembar muat 54 pcs)',
      },
    ],
    subtotal: 410000,
    discount: 10000,
    tax: 0,
    total: 400000,
    paidAmount: 400000,
    balance: 0,
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    status: 'completed',
    priority: 'normal',
    deadline: new Date(Date.now() - 86400000).toISOString(),
    createdBy: 'Sinta (Kasir / Admin)',
    designerName: 'Dimas (Designer Grafis)',
    operatorName: 'Budi (Operator Cetak)',
    designStatus: 'approved',
    pickupType: 'pickup',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    timeline: [
      {
        id: 'TL-8',
        timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
        status: 'pending',
        user: 'Sinta (Kasir)',
        userRole: 'admin',
        note: 'Order diterima lunas tunai',
      },
      {
        id: 'TL-9',
        timestamp: new Date(Date.now() - 86400000).toISOString(),
        status: 'completed',
        user: 'Sinta (Kasir)',
        userRole: 'admin',
        note: 'Pesanan telah diambil oleh Ibu Ratna',
      },
    ],
  },
  {
    id: 'ORD-005',
    orderNumber: 'INV-202608-0005',
    spkNumber: 'SPK-202608-0005',
    customerId: 'CUST-004',
    customerName: 'Sekolah Bintang Harapan',
    customerPhone: '081399887766',
    customerType: 'corporate',
    items: [
      {
        id: 'ITEM-005',
        category: 'large_format',
        productName: 'Standing X-Banner Penerimaan Siswa Baru',
        materialName: 'Albatros Matte + Rangka X-Banner',
        qty: 4,
        unit: 'pcs',
        unitPrice: 75000,
        subtotal: 300000,
        finishingNames: ['Laminasi Doff A3+'],
        finishingCost: 0,
        designFee: 0,
        designType: 'ready_to_print',
        targetMachine: 'Epson SureColor S80670 (Indoor 9 Color)',
        notes: 'Hasil tajam indoor foto anak-anak',
      },
      {
        id: 'ITEM-006',
        category: 'offset_doc',
        productName: 'Nota Pembayaran SPP (2 Ply NCR)',
        materialName: 'Nota 2 Ply NCR (Per Buku 50 Set)',
        qty: 15,
        unit: 'buku',
        unitPrice: 14000,
        subtotal: 210000,
        finishingNames: [],
        finishingCost: 0,
        designFee: 0,
        designType: 'ready_to_print',
        notes: 'Nomorator mulai dari 001 - 750',
      },
    ],
    subtotal: 510000,
    discount: 10000,
    tax: 0,
    total: 500000,
    paidAmount: 0,
    balance: 500000,
    paymentStatus: 'unpaid',
    paymentMethod: 'tempo',
    status: 'finishing',
    priority: 'normal',
    deadline: new Date(Date.now() + 86400000).toISOString(),
    createdBy: 'Sinta (Kasir / Admin)',
    operatorName: 'Budi (Operator Cetak)',
    designStatus: 'approved',
    pickupType: 'delivery',
    deliveryAddress: 'Jl. Pendidikan No. 45, Bagian Tata Usaha',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    timeline: [
      {
        id: 'TL-10',
        timestamp: new Date(Date.now() - 3600000 * 12).toISOString(),
        status: 'pending',
        user: 'Sinta (Kasir)',
        userRole: 'admin',
        note: 'Order SPP Tempo Yayasan masuk',
      },
      {
        id: 'TL-11',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        status: 'finishing',
        user: 'Budi (Operator)',
        userRole: 'operator',
        note: 'Cetak selesai, masuk tahap pasang rangka X-Banner & jilid lem buku nota',
      },
    ],
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'EXP-001',
    expenseNumber: 'KAS-OUT-202608-01',
    category: 'bahan_baku',
    description: 'Beli 3 Roll Bahan Flexi 280gr 3.2m x 50m (Supplier Jaya Grafika)',
    amount: 2250000,
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    createdBy: 'Yahya (Owner)',
    paymentMethod: 'transfer',
  },
  {
    id: 'EXP-002',
    expenseNumber: 'KAS-OUT-202608-02',
    category: 'tinta',
    description: 'Beli Tinta Solvent 4 Warna (CMYK) @ 5 Liter',
    amount: 1400000,
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    createdBy: 'Yahya (Owner)',
    paymentMethod: 'transfer',
  },
  {
    id: 'EXP-003',
    expenseNumber: 'KAS-OUT-202608-03',
    category: 'listrik_utilitas',
    description: 'Token Listrik PLN Daya 11.000 VA Workshop',
    amount: 750000,
    date: new Date(Date.now() - 86400000 * 5).toISOString(),
    createdBy: 'Sinta (Kasir / Admin)',
    paymentMethod: 'cash',
  },
];

export const initialStoreSettings: StoreSettings = {
  storeName: 'GFX GRAPHIC',
  appName: 'GFX GRAPHIC',
  appIcon: './favicon.ico',
  appSubtitle: 'Percetakan & Digital Printing',
  tagline: 'Solusi Cepat & Berkualitas Segala Kebutuhan Cetak Anda',
  phone: '085163594245',
  whatsapp: '085163594245',
  email: 'gfxgraphic@gmail.com',
  address: 'Dusun Ciangir, Kec. Cikoneng Kab. Ciamis Provinsi Jawa Barat Pos 4621',
  city: 'Ciamis, Jawa Barat',
  bankAccounts: [
    {
      bankName: 'BCA',
      accountNumber: '1300551272',
      accountHolder: 'MUHAMAD YAHYA',
    },
    {
      bankName: 'DANA',
      accountNumber: '085723574540',
      accountHolder: 'MUHAMAD YAHYA',
    },
  ],
  footerReceiptNotes: 'Barang yang sudah dicetak tidak dapat dikembalikan. Harap simpan nota ini untuk bukti pengambilan.',
  footerSpkNotes: 'Pastikan file sudah sesuai resolusi dan batas aman potong. Cek bahan dan finishing sebelum diserahkan ke QC.',
  taxEnabled: false,
  taxPercent: 11,
};

export const initialPurchaseOrders: any[] = [
  {
    id: 'PO-001',
    poNumber: 'PO-20260825-001',
    date: '2026-08-25',
    supplierName: 'PT. Multi Visual Sinar (Distributor Flexi)',
    supplierPhone: '021-5591234',
    supplierAddress: 'Kawasan Industri Cengkareng Blok B3 No. 8, Jakarta Barat',
    supplierContactPerson: 'Bpk. Hendra Gunawan',
    items: [
      {
        id: 'POI-001',
        itemName: 'Flexi China 280gr (Roll 3.2m x 50m)',
        category: 'large_format',
        qty: 3,
        unit: 'roll',
        unitPrice: 1200000,
        subtotal: 3600000,
        notes: 'Lebar 3.2 meter, panjang 50 meter per roll (160 m²)',
      },
      {
        id: 'POI-002',
        itemName: 'Flexi Korchin / Korea 440gr (Roll 3.2m x 50m)',
        category: 'large_format',
        qty: 2,
        unit: 'roll',
        unitPrice: 2400000,
        subtotal: 4800000,
        notes: 'Flexi tebal serat doff halus',
      },
    ],
    subtotal: 8400000,
    taxPercent: 0,
    taxAmount: 0,
    shippingCost: 150000,
    totalAmount: 8550000,
    paymentTerms: 'tempo_14',
    status: 'received',
    notes: 'Kirim via Lalamove / Truk ekspedisi langsung ke workshop',
    createdBy: 'Sinta (Kasir / Admin)',
    approvedBy: 'Yahya (Owner)',
    receivedDate: '2026-08-26T14:30:00.000Z',
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'PO-002',
    poNumber: 'PO-20260827-002',
    date: '2026-08-27',
    supplierName: 'CV. Sumber Tinta Grafika',
    supplierPhone: '022-7304411',
    supplierAddress: 'Jl. Soekarno Hatta No. 421, Bandung',
    supplierContactPerson: 'Ibu Ratna',
    items: [
      {
        id: 'POI-003',
        itemName: 'Tinta Outdoor Solvent Seiko 510 35pl (Set CMYK)',
        category: 'tinta',
        qty: 2,
        unit: 'set',
        unitPrice: 1800000,
        subtotal: 3600000,
        notes: '1 set isi 4 botol @ 5 Liter (C, M, Y, K)',
      },
      {
        id: 'POI-004',
        itemName: 'Mata Ayam / Eyelet Banner 10mm (Dus)',
        category: 'perlengkapan',
        qty: 5,
        unit: 'box',
        unitPrice: 85000,
        subtotal: 425000,
        notes: 'Isi 1.000 pcs per dus nikel silver anti-karat',
      },
    ],
    subtotal: 4025000,
    taxPercent: 0,
    taxAmount: 0,
    shippingCost: 50000,
    totalAmount: 4075000,
    paymentTerms: 'cod',
    status: 'sent',
    notes: 'Harap dikirim siang ini pukul 13.00 WIB',
    createdBy: 'Sinta (Kasir / Admin)',
    approvedBy: 'Yahya (Owner)',
    createdAt: '2026-08-27T08:30:00.000Z',
  },
];

export const initialShifts: any[] = [
  {
    id: 'SHIFT-001',
    shiftNumber: 'SHIFT-20260826-01',
    cashierId: 'USR-002',
    cashierName: 'Sinta (Kasir / Admin)',
    startTime: '2026-08-26T08:00:00.000Z',
    endTime: '2026-08-26T17:00:00.000Z',
    status: 'closed',
    openingCash: 200000,
    totalCashSales: 1650000,
    totalNonCashSales: 1200000,
    totalExpenses: 50000,
    expectedCash: 1800000,
    actualCash: 1800000,
    difference: 0,
    notes: 'Modal awal uang kembalian pecahan 5rb, 10rb, 20rb',
    closingNotes: 'Kas seimbang pas, uang fisik disetor ke Pak Yahya (Owner)',
    createdAt: '2026-08-26T08:00:00.000Z',
    updatedAt: '2026-08-26T17:00:00.000Z',
  },
];

export const initialProductionBills: any[] = [
  {
    id: 'BILL-001',
    billNumber: 'TGH-202608-001',
    title: 'Ongkos Jahit Jersey Satuan (10 Pcs)',
    workerName: 'Pak Joko (Penjahit)',
    workerPhone: '081234567890',
    type: 'satuan',
    qty: 10,
    unitPrice: 35000,
    totalAmount: 350000,
    status: 'unpaid',
    createdAt: '2026-08-27T09:00:00.000Z',
    notes: 'Ongkos jahit baju jersey futsal bordir & kerah rib',
  },
  {
    id: 'BILL-002',
    billNumber: 'TGH-202608-002',
    title: 'Finishing Seaming & Mata Ayam Banner 3x1m',
    workerName: 'Mas Budi (Finishing Banner)',
    workerPhone: '085698712345',
    type: 'meter',
    lengthM: 3,
    widthM: 1,
    qty: 10,
    unitPrice: 2500,
    totalAmount: 75000,
    status: 'unpaid',
    createdAt: '2026-08-27T10:30:00.000Z',
    notes: 'Total luas 30 m² (10 lembar banner 3x1m)',
  },
];

export const initialWorkerDebts: any[] = [
  {
    id: 'DEBT-001',
    debtNumber: 'HTG-202608-001',
    workerName: 'Pak Joko (Penjahit)',
    phone: '081234567890',
    initialAmount: 500000,
    remainingAmount: 500000,
    createdAt: '2026-08-25T14:00:00.000Z',
    notes: 'Kasbon operasional pribadi awal pekan',
    history: [
      {
        id: 'HIST-001',
        date: '2026-08-25T14:00:00.000Z',
        amount: 500000,
        description: 'Pinjaman Kasbon Awal',
      },
    ],
  },
  {
    id: 'DEBT-002',
    debtNumber: 'HTG-202608-002',
    workerName: 'Mas Budi (Finishing Banner)',
    phone: '085698712345',
    initialAmount: 200000,
    remainingAmount: 200000,
    createdAt: '2026-08-26T11:00:00.000Z',
    notes: 'Kasbon harian perlengkapan lem',
    history: [
      {
        id: 'HIST-002',
        date: '2026-08-26T11:00:00.000Z',
        amount: 200000,
        description: 'Pinjaman Kasbon Awal',
      },
    ],
  },
];
